### ISSUE TITLE
flaskcode example

### ISSUE THREAD

**Issue by sbohora** [sujeetkv/flaskcode#1]
@sujeetkv: Can you provide more examples and documentation how this works?  Thanks.

**Comment by sujeetkv** [comment]
Install the package using pip: `pip install flaskcode`
then run command: `flaskcode /path/to/resource/folder` for example `flaskcode /home/user/demoproject`
It will launch a web app to edit the files of given folder path.

You can integrate this in your flask application given your folder path in config as specified in README file.

As simple as that.
