### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by i2blind** [sujeetkv/flaskcode#3]
This is a really nice tool.  When you get time could you add the ability to edit .yaml or .yml files.  My work around for now is to link the files as .txt.  It understands yaml just fine just won't open them.

Thank you.
Brent

**Comment by sujeetkv** [comment]
Editing .yaml and .yml files is already supported.

**Comment by i2blind** [comment]
Sure but it will not open a file ending in .yml or .yaml.  Yiu have to name it .txt

**Comment by sujeetkv** [comment]
It works well with file names ending with .yml and .yaml. You can see it in attached screenshots. You might be doing something wrong.

![flaskcode-yaml-support](https://user-images.githubusercontent.com/17122995/82913804-6069b680-9f8c-11ea-996f-ed17f0366ff1.png)
![flaskcode-yml-support](https://user-images.githubusercontent.com/17122995/82913811-619ae380-9f8c-11ea-81ed-5e49d8b297be.png)
