### ISSUE TITLE
Adds whitespace and new lines while saving .txt file

### ISSUE THREAD

**Issue by intelliroot-tech** [sujeetkv/flaskcode#4]
While adding any data to .txt files , an additional white space and newline gets appended. 

![snapshot1](https://user-images.githubusercontent.com/62929839/89581438-9a8ce980-d854-11ea-850b-1e4cf684db6e.JPG)
 and newline gets appended.

**Comment by greg121** [comment]
I have the same issue.

**Comment by greg121** [comment]
https://stackoverflow.com/questions/4025760/python-file-write-creating-extra-carriage-return/41248005

this seems to be a problem on Windows. 

`with open(filepath, 'w', **newline='\n'**) as dest:`

I added this in utils.py in write_file(..) and it now works for me.

**Comment by sujeetkv** [comment]
I have fixed this issue 51f67ab276c45298ca9d586548d53da9bec22575.

**Comment by sujeetkv** [comment]
I am closing this issue. Feel free to re-open again for any issue.
