### ISSUE TITLE
german umlaute (ü, ä, ö) are replaced when file is saved

### ISSUE THREAD

**Issue by greg121** [sujeetkv/flaskcode#6]
german umlaute (ü, ä, ö) are replaced by � when file is saved.

**Comment by greg121** [comment]
in write_file(..) in utils.py 
`with open(filepath, 'w', encoding='utf-8') as dest:`
worked for me

**Comment by sujeetkv** [comment]
I have fixed this issue 51f67ab276c45298ca9d586548d53da9bec22575.
